<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQF2I4D\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQF2I4D/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQF2I4D.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQF2I4D\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIQF2I4D\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IQF2I4D',
    'container.build_id' => 'bdcf6cf8',
    'container.build_time' => 1646723676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQF2I4D');
