<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2oLxxN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2oLxxN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL2oLxxN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL2oLxxN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL2oLxxN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'L2oLxxN',
    'container.build_id' => 'df4e8daa',
    'container.build_time' => 1646680042,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2oLxxN');
